scrape_configs:
  - job_name: 'with_session'

    session: 
      enabled: true
      batch_size: 100
      threads: 10 

    scrape_interval: 60s
    scrape_timeout: 50s

    honor_labels: true
    metrics_path: '/federate'

    params:
      'match[]':
        - '{__name__=~"ow_wt_analytics.*"}'

    static_configs:
      - targets:
#        - '10.70.128.65:32600'
        - '10.100.141.165:9091'
